version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - cd complete
      - ./gradlew bootJar

artifacts:
  files:
    - complete/build/libs/gs-accessing-data-rest-0.1.0.jar
