version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - ./gradlew bootRepackage

artifacts:
  files:
    - build/libs/gs-accessing-data-rest-0.1.0.jar
